export { default as Footer } from './Footer/Footer'
export { default as Header } from './Header/Header'
export { default as Hero } from './Hero/Hero'
export { default as ProductsList } from './ProductsList/ProductsList'
export { default as ProductsHeader } from './ProductsHeader/ProductsHeader'
export { default as Cart } from './Cart/Cart'