export { default as Account } from './Account/Account'
export { default as Auth } from './Auth/Auth'
export { default as Checkout } from './Checkout/Checkout'
export { default as Home } from './Home/Home'
export { default as Product } from './Product/Product'
export { default as Products } from './Products/Products'